# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '12.x'
      - run: |
            npm install
            npm run build
            pwd
            cd dist
            git config --global user.email "aryashreep@gmail.com" > /dev/null 2>&1
            git config --global user.name "aryashreep" > /dev/null 2>&1
            git init
            git remote add --fetch origin git@github.com:aryashreep/japa.git
            git checkout --orphan main
            git add -A
            git commit --allow-empty -m "Deploy to Japa (`date '+%F %T %Z'`) [ci skip]"
            git push --force --quiet origin main > /dev/null 2>&1
            echo "Deployment finished!"
